"""
config.py

Per-model configuration. This file is generated by factory_TLM.py when
the model is created -- the placeholder tokens below get replaced with
real values -- feel free to hand-edit it afterward before running
train.py.
"""

MODEL_NAME = "__MODEL_NAME__"

# --- Architecture -----------------------------------------------------
# Read by train.py on its first run to construct TinyTransformer
# (see architecture.py). vocab_size is NOT set here -- it comes from
# len(vocab) in this model's tokenize_vocab.json once tokenizer.py has
# been run, since it isn't known at creation time.
D_MODEL = __D_MODEL__
NUM_LAYERS = __NUM_LAYERS__
NUM_HEADS = __NUM_HEADS__
D_FF = __D_FF__
MAX_SEQ_LEN = __MAX_SEQ_LEN__

# --- Compute backend ----------------------------------------------------
DEVICE = "__DEVICE__"   # "cpu", "cugpu" (AMD/Intel/NVIDIA), or "gpu" (CuPy/CUDA)

# --- Training defaults (train.py may still expose CLI overrides) --------
SEQ_LENGTH = __SEQ_LENGTH__       # tokens of context per training step
BATCH_SIZE = __BATCH_SIZE__       # sequences trained on at once per step
LEARNING_RATE = __LEARNING_RATE__
EPOCHS = __EPOCHS__
